#Tomcat
server:
  tomcat:
    max-threads: 10
    min-spare-threads: 10
  port: 7777

#mysql
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/travel?characterEncoding=UTF-8&serverTimezone=UTC
    username: yh
    password: 123456
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  thymeleaf:
    mode: LEGACYHTML5
    cache: false

#mybatis
mybatis:
  mapperLocations: classpath:mapper/**/*.xml